chore: bump verson to 1.1.5
linuxdeepin/dde-appearance pull request #67
Opened 2023-08-08 06:15 UTC by Decodetalkers

Log:

2023-08-08 08:15 UTC, Decodetalkers commented
/check obs

2023-08-09 01:43 UTC, dengbo11 requested changes

2023-08-09 01:43 UTC, dengbo11 commented on debian/changelog
> + -- chenhongtao <chenhongtao@deepin.org>  The, 8 Aug 2023 14:14:20 +0800
星期二写错了， 应该是Tue吧

2023-08-09 02:08 UTC, Decodetalkers commented on debian/changelog
> + -- chenhongtao <chenhongtao@deepin.org>  The, 8 Aug 2023 14:14:20 +0800
啊，昨天脑子没有转过弯，写错了

2023-08-09 07:46 UTC, dengbo11 submitted a review, later dismissed

2023-08-15 03:49 UTC, chenchongbiao commented
linuxdeepin/developer-center/issues/5181
测试通过了 可以合并

2023-08-15 05:20 UTC, dengbo11 approved these changes

2023-08-15 05:20 UTC, merged